### ISSUE TITLE
Zappa + Starlette

### ISSUE THREAD

**Issue by MihaZelnik** [erm/mangum#37]
Anyone tried using Zappa to deploy Starlette with Mangum?

I can't figure it out how to do it, or it is even possible to do it

**Comment by erm** [comment]
@MihaZelnik it is currently not possible since Zappa does not support ASGI applications. There is an open issue on the Zappa tracker [here](https://github.com/Miserlou/Zappa/issues/649) that discusses WebSockets/Channels. I am unaware of any plans to implement ASGI support in Zappa, but I think it would be great because I've had good experiences with the configuration/deployment tooling it provides. 

I'll leave this issue open to track any progress with Zappa + ASGI, because it will likely inform how much tooling I end up providing in Mangum.

**Comment by delijati** [comment]
I added it in my Zappa branch https://github.com/delijati/Zappa. Here i played a bit around with it https://github.com/delijati/benchmark :)
